"""Differential check: print the Python original's results for every case in
test_string_literals.py's `test_canonical_literals`, in a form a Rust test can
assert directly.

Run from the KumoSQL repo:
    python tools/dump_literal_cases.py

Writes a Rust-ready `CASES` table on stdout.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

# The Python original lives next to this repository and is read-only: import and
# parse it, never write to it.
REFERENCE = Path(__file__).resolve().parents[2] / "KumoSQL"
sys.path.insert(0, str(REFERENCE / "src"))

from kumosql.string_literals import canonical_literals, invalid_literal  # noqa: E402

# Cases are read straight out of the Python test file with `ast`, never retyped:
# transcription by hand silently corrupted two of them.
TEST_FILE = REFERENCE / "tests" / "test_string_literals.py"

# Where the generated Rust table is written, relative to this repository root.
OUTPUT = Path("crates/kumosql-sql/tests/generated/literal_cases.rs")


def _eval_str(node: ast.expr) -> str:
    """Evaluate a string expression, allowing the ``a + b + c`` concatenation
    the test file uses to build one of its expected values.

    `ast.literal_eval` alone refuses this, because it rejects `BinOp`.
    """
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return _eval_str(node.left) + _eval_str(node.right)
    if isinstance(node, ast.Tuple):
        return "".join(_eval_str(e) for e in node.elts)
    raise ValueError(f"not a string expression: {ast.dump(node)}")


def load_cases() -> list[tuple[str, str]]:
    """Extract the `(sql, expected)` pairs from `test_canonical_literals`."""
    tree = ast.parse(TEST_FILE.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or node.name != "test_canonical_literals":
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            for arg in decorator.args:
                if not isinstance(arg, (ast.List, ast.Tuple)) or not arg.elts:
                    continue
                rows = [_eval_str(e) for e in arg.elts]
                # Each row is a 2-tuple, which `_eval_str` flattens; regroup.
                if all(isinstance(e, ast.Tuple) and len(e.elts) == 2 for e in arg.elts):
                    return [
                        (_eval_str(row.elts[0]), _eval_str(row.elts[1])) for row in arg.elts
                    ]
                del rows
    raise SystemExit(f"could not find the parametrize cases in {TEST_FILE}")


def rust_str(value: str) -> str:
    """Render a Python str as a Rust raw string literal.

    A raw string is `r`, then as many `#` as needed, then the quote, the value,
    the quote, then the same `#` count. The hash count must exceed the longest
    run of `#` immediately after a `"` in the value, otherwise the literal ends
    early -- for `SELECT 'a"b'` that means `r#"..."#`, never `r"#...`.
    """
    for count in range(0, 5):
        hashes = "#" * count
        if f'"{hashes}' not in value:
            return f'r{hashes}"{value}"{hashes}'
    raise ValueError("cannot render as a Rust raw string")


def main() -> int:
    failures = 0
    cases = load_cases()

    lines = [
        "// Generated by tools/dump_literal_cases.py from the Python original's",
        "// tests/test_string_literals.py. Do not edit by hand: fix the Rust port or",
        "// regenerate, so the cases stay byte-identical to the reference.",
        "//",
        "// Self-check against the Python original:",
    ]
    body = ["const CANONICAL_CASES: &[(&str, &str)] = &["]
    for sql, expected in cases:
        actual = canonical_literals(sql)
        if actual != expected:
            failures += 1
            body.append(f"// MISMATCH for {sql!r}: got {actual!r}, expected {expected!r}")
        body.append(f"    ({rust_str(sql)}, {rust_str(expected)}),")
    body.append("];")
    lines += [f"//   {len(cases)} cases, {failures} mismatch(es)"]

    for sql, want in (
        ("SELECT 'a\nb' AS v FROM t", True),
        ("SELECT '''a\nb''' AS v FROM t", False),
        ("SELECT 1\nFROM t", False),
        ("SELECT 1 -- a comment\nFROM t", False),
        ("SELECT 1 /* a\ncomment */ FROM t", False),
        ("SELECT `a\nb` FROM t", False),
    ):
        got = invalid_literal(sql)
        if got != want:
            failures += 1
            print(f"// MISMATCH for invalid_literal({sql!r}): got {got}, expected {want}")
    lines.append(f"// invalid_literal cases checked, {failures} total mismatch(es)")

    output = Path(__file__).resolve().parents[1] / OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines + body) + "\n", encoding="utf-8")
    print(f"wrote {output} ({len(cases)} cases, {failures} mismatch(es))")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())